// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DialogSampleApp.Resource", IsApplication=true)]

namespace DialogSampleApp
{
	
	
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int DarkBrown = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int DarkRed = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int Gold = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int LightBrown = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int creme = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int listseparator = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int menufinderred = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020003
			public const int focused = 2130837507;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020004
			public const int selected = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_BoolField = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int dialog_Button = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_DisclosureField = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int dialog_ImageLeft = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageRight = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelField = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dialog_LabelSubtextField = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int dialog_Panel = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_RadioButtonList = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int dialog_SliderField = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_Spinner = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int dialog_ValueField = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int dialog_listView = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int dialog_progressbar = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int iFormFieldValue = 2131099661;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_boolfieldleft = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldright = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldsubleft = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubright = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_button = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_datefield = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_fieldsetlabel = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_floatimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_labelfieldbelow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldright = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_onofffieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_panel = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_progressbar = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_root = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_selectlist = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_selectlistfield = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textarea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_textfieldbelow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textfieldright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int main = 2130903059;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			private String()
			{
			}
		}
	}
}
